#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 31 13:38:21 2022

@author: wangyuanjing
"""
#练习1
def right_justify(s):
    l = len(s)
    print(' '*(70-l)+s) 
    right_justify('monty')
#练习2
def do_twice(a):
    a()
    a()
 #练习3   
def print_spam():
    print('spam')
do_twice(print_spam)

def do_twice(f,x):
    f(x)
    f(x)
	
def print_spam(x):
    print(x)
    
do_twice(print_spam,'spam')

def do_twice(f,x):
    f(x)
    f(x)

def do_four(f,x):
	do_twice(f,x)
	do_twice(f,x)
	
def print_spam(x):
    print(x)

do_four(print_spam,'spam')






